# Generated by Django 4.2.3 on 2023-07-19 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID_film", models.IntegerField()),
                ("titre", models.CharField(max_length=100)),
                ("resume", models.CharField(max_length=500)),
                ("duree", models.IntegerField()),
                ("estSpecial", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID_salle", models.IntegerField()),
                ("nom", models.CharField(max_length=20)),
                ("capacite", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID_user", models.IntegerField()),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("mdp", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID_seance", models.IntegerField()),
                ("date", models.DateField()),
                ("heure", models.TimeField()),
                ("prix", models.FloatField()),
                (
                    "ID_film",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemaApp.film",
                    ),
                ),
                (
                    "ID_salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cinemaApp.salle",
                    ),
                ),
            ],
        ),
    ]
