# Generated by Django 4.2.3 on 2023-07-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinemaApp", "0002_rename_user_utilisateur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Siege",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ID_siege", models.IntegerField()),
                ("numero", models.IntegerField()),
                (
                    "ID_salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cinemaApp.salle",
                    ),
                ),
            ],
        ),
    ]
